# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 731a40ae10f308fa9873ad2b8810d3524b778472e0c805872663a0903ce9808ea60ea6742a5f071b953585d3c190ef9961e9f7dc3f39de1d5f5b77817034ae0b

test:
  secret_key_base: 29b81462882cc1056412e1c359add09ad467faa79ff3f7280d6938e074ac7d7f45bff10fe8c639b035edf8abc7b63899a0229e3c68b17a62c2d9fb5702a9a7a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
